2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Configure stats pid to 55744
2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Loading settings from /home/ziyar/.config/wandb/settings
2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Loading settings from /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/settings
2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'aerial_gym/rl_training/sample_factory/aerialgym_examples/train_aerialgym_custom_net.py', 'program': 'train_aerialgym_custom_net.py'}
2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_init.py:_log_setup():461] Logging user logs to /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112351-4_envs_wandb_training_20250629_112350_423826/logs/debug.log
2025-06-29 11:23:51,350 INFO    MainThread:55744 [wandb_init.py:_log_setup():462] Logging internal logs to /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112351-4_envs_wandb_training_20250629_112350_423826/logs/debug-internal.log
2025-06-29 11:23:51,351 INFO    MainThread:55744 [wandb_init.py:init():495] calling init triggers
2025-06-29 11:23:51,351 INFO    MainThread:55744 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2025-06-29 11:23:51,352 INFO    MainThread:55744 [wandb_init.py:init():548] starting backend
2025-06-29 11:23:51,352 INFO    MainThread:55744 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2025-06-29 11:23:51,361 INFO    MainThread:55744 [backend.py:ensure_launched():217] starting backend process...
2025-06-29 11:23:51,377 INFO    MainThread:55744 [backend.py:ensure_launched():222] started backend process with pid: 55879
2025-06-29 11:23:51,378 INFO    MainThread:55744 [wandb_init.py:init():558] backend started and connected
2025-06-29 11:23:51,384 INFO    MainThread:55744 [wandb_init.py:init():634] updated telemetry
2025-06-29 11:23:51,387 INFO    MainThread:55879 [internal.py:wandb_internal():90] W&B internal server running at pid: 55879, started at: 2025-06-29 11:23:51.386306
2025-06-29 11:23:51,392 INFO    WriterThread:55879 [datastore.py:open_for_write():75] open: /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112351-4_envs_wandb_training_20250629_112350_423826/run-4_envs_wandb_training_20250629_112350_423826.wandb
2025-06-29 11:23:51,431 INFO    MainThread:55744 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2025-06-29 11:23:51,436 INFO    SenderThread:55879 [sender.py:_maybe_setup_resume():493] checking resume status for ziya-ruso-ucl-org/aerialgym/4_envs_wandb_training_20250629_112350_423826
2025-06-29 11:23:51,713 ERROR   SenderThread:55879 [internal_api.py:execute():161] 400 response executing GraphQL.
2025-06-29 11:23:51,713 ERROR   SenderThread:55879 [internal_api.py:execute():162] {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-06-29 11:23:52,434 INFO    HandlerThread:55879 [handler.py:finish():806] shutting down handler
2025-06-29 11:23:52,439 INFO    WriterThread:55879 [datastore.py:close():279] close: /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112351-4_envs_wandb_training_20250629_112350_423826/run-4_envs_wandb_training_20250629_112350_423826.wandb
2025-06-29 11:23:52,440 ERROR   MainThread:55879 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 238, in send
    send_handler(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 696, in send_run
    self._init_run(run, config_value_dict)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 720, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 27, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [400]>
2025-06-29 11:24:21,433 INFO    MainThread:55744 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2025-06-29 11:24:21,433 ERROR   MainThread:55744 [wandb_init.py:init():674] backend process timed out
2025-06-29 11:24:21,433 ERROR   MainThread:55744 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
2025-06-29 11:24:21,460 ERROR   MainThread:55744 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    backend.cleanup()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2025-06-29 11:24:24,023 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Configure stats pid to 55744
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Loading settings from /home/ziyar/.config/wandb/settings
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Loading settings from /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/settings
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'aerial_gym/rl_training/sample_factory/aerialgym_examples/train_aerialgym_custom_net.py', 'program': 'train_aerialgym_custom_net.py'}
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_init.py:_log_setup():461] Logging user logs to /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112424-4_envs_wandb_training_20250629_112350_423826/logs/debug.log
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_init.py:_log_setup():462] Logging internal logs to /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112424-4_envs_wandb_training_20250629_112350_423826/logs/debug-internal.log
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_init.py:init():495] calling init triggers
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2025-06-29 11:24:24,024 INFO    MainThread:55744 [wandb_init.py:init():548] starting backend
2025-06-29 11:24:24,024 INFO    MainThread:55744 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2025-06-29 11:24:24,027 INFO    MainThread:55744 [backend.py:ensure_launched():217] starting backend process...
2025-06-29 11:24:24,042 INFO    MainThread:55744 [backend.py:ensure_launched():222] started backend process with pid: 56087
2025-06-29 11:24:24,043 INFO    MainThread:55744 [wandb_init.py:init():558] backend started and connected
2025-06-29 11:24:24,049 INFO    MainThread:56087 [internal.py:wandb_internal():90] W&B internal server running at pid: 56087, started at: 2025-06-29 11:24:24.048169
2025-06-29 11:24:24,050 INFO    MainThread:55744 [wandb_init.py:init():634] updated telemetry
2025-06-29 11:24:24,052 INFO    WriterThread:56087 [datastore.py:open_for_write():75] open: /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112424-4_envs_wandb_training_20250629_112350_423826/run-4_envs_wandb_training_20250629_112350_423826.wandb
2025-06-29 11:24:24,089 INFO    MainThread:55744 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2025-06-29 11:24:24,092 INFO    SenderThread:56087 [sender.py:_maybe_setup_resume():493] checking resume status for ziya-ruso-ucl-org/aerialgym/4_envs_wandb_training_20250629_112350_423826
2025-06-29 11:24:24,418 ERROR   SenderThread:56087 [internal_api.py:execute():161] 400 response executing GraphQL.
2025-06-29 11:24:24,419 ERROR   SenderThread:56087 [internal_api.py:execute():162] {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-06-29 11:24:25,091 INFO    WriterThread:56087 [datastore.py:close():279] close: /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112424-4_envs_wandb_training_20250629_112350_423826/run-4_envs_wandb_training_20250629_112350_423826.wandb
2025-06-29 11:24:25,092 INFO    HandlerThread:56087 [handler.py:finish():806] shutting down handler
2025-06-29 11:24:25,092 ERROR   MainThread:56087 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 238, in send
    send_handler(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 696, in send_run
    self._init_run(run, config_value_dict)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 720, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 27, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [400]>
2025-06-29 11:24:26,320 WARNING MainThread:55744 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 668, in init
    run_result = backend.interface.communicate_run(
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 223, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
