2025-06-29 11:26:35,941 INFO    MainThread:57107 [internal.py:wandb_internal():90] W&B internal server running at pid: 57107, started at: 2025-06-29 11:26:35.940027
2025-06-29 11:26:35,945 INFO    WriterThread:57107 [datastore.py:open_for_write():75] open: /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112635-4_envs_wandb_training_20250629_112635_056531/run-4_envs_wandb_training_20250629_112635_056531.wandb
2025-06-29 11:26:35,945 DEBUG   SenderThread:57107 [sender.py:send():236] send: header
2025-06-29 11:26:35,991 DEBUG   SenderThread:57107 [sender.py:send():236] send: run
2025-06-29 11:26:35,995 INFO    SenderThread:57107 [sender.py:_maybe_setup_resume():493] checking resume status for ziya-ruso/aerialgym-dce-navigation-ziya/4_envs_wandb_training_20250629_112635_056531
2025-06-29 11:26:36,265 ERROR   SenderThread:57107 [internal_api.py:execute():161] 403 response executing GraphQL.
2025-06-29 11:26:36,265 ERROR   SenderThread:57107 [internal_api.py:execute():162] {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-06-29 11:26:36,991 INFO    HandlerThread:57107 [handler.py:finish():806] shutting down handler
2025-06-29 11:26:37,001 INFO    WriterThread:57107 [datastore.py:close():279] close: /home/ziyar/aerialgym/aerialgym_ws/src/aerial_gym_simulator/aerial_gym/rl_training/sample_factory/aerialgym_examples/wandb/run-20250629_112635-4_envs_wandb_training_20250629_112635_056531/run-4_envs_wandb_training_20250629_112635_056531.wandb
2025-06-29 11:26:37,001 ERROR   MainThread:57107 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 124, in __call__
    if not check_retry_fn(e):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/util.py", line 887, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 238, in send
    send_handler(record)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 696, in send_run
    self._init_run(run, config_value_dict)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 720, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 61, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 124, in __call__
    if not check_retry_fn(e):
  File "/home/ziyar/miniforge3/envs/aerialgym/lib/python3.8/site-packages/wandb/util.py", line 887, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
